modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="diamondenriched_steel"
version="1.0.0"
displayName="Diamond-Enriched Steel"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="nitro_dynamite18"
description='''
This pack adds two new materials: Steel and Diamond-Enriched Steel.
'''

[[dependencies.diamondenriched_steel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




